"""S7 salary component and structure

Revision ID: 2797ca8c8660
Revises: 089dead90284
Create Date: 2026-07-19 22:34:09.681224

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2797ca8c8660"
down_revision: str | None = "089dead90284"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salary_component_def",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "component_type",
            sa.Enum(
                "BASE",
                "PERFORMANCE",
                "POSITION",
                "ALLOWANCE",
                "OVERTIME",
                "DEDUCTION",
                name="component_type",
            ),
            nullable=False,
        ),
        sa.Column("taxable", sa.Boolean(), nullable=False),
        sa.Column("in_social_base", sa.Boolean(), nullable=False),
        sa.Column("in_housing_base", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "employee_salary_structure",
        sa.Column("employee_id", sa.BigInteger(), nullable=False),
        sa.Column("component_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["salary_component_def.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "employee_id", "component_id", "effective_from", name="uq_ess_emp_comp_from"
        ),
    )
    op.create_index(
        op.f("ix_employee_salary_structure_component_id"),
        "employee_salary_structure",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_salary_structure_employee_id"),
        "employee_salary_structure",
        ["employee_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_employee_salary_structure_employee_id"), table_name="employee_salary_structure"
    )
    op.drop_index(
        op.f("ix_employee_salary_structure_component_id"), table_name="employee_salary_structure"
    )
    op.drop_table("employee_salary_structure")
    op.drop_table("salary_component_def")
    sa.Enum(name="component_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
