"""S2 core schema

Revision ID: dbe89a9edcdc
Revises: 
Create Date: 2026-07-17 06:04:07.047935

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dbe89a9edcdc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_grade',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('org_unit',
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('GROUP', 'REGION', 'STORE', name='org_type'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_org_unit_parent_id'), 'org_unit', ['parent_id'], unique=False)
    op.create_table('pay_period',
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CALCULATING', 'CLOSED', 'PAID', name='period_status'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pay_period_year_month'), 'pay_period', ['year_month'], unique=True)
    op.create_table('employee',
    sa.Column('emp_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('org_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('job_grade_id', sa.BigInteger(), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME_HOURLY', 'LABOR', name='employment_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESIGNED', 'SUSPENDED', name='employee_status'), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('probation_end', sa.Date(), nullable=True),
    sa.Column('leave_date', sa.Date(), nullable=True),
    sa.Column('social_city', sa.String(length=32), nullable=True),
    sa.Column('id_card_enc', sa.String(length=512), nullable=True),
    sa.Column('bank_account_enc', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_grade_id'], ['job_grade.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_emp_no'), 'employee', ['emp_no'], unique=True)
    op.create_index(op.f('ix_employee_job_grade_id'), 'employee', ['job_grade_id'], unique=False)
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=False)
    op.create_index(op.f('ix_employee_org_unit_id'), 'employee', ['org_unit_id'], unique=False)
    op.create_table('salary_band',
    sa.Column('job_grade_id', sa.BigInteger(), nullable=False),
    sa.Column('band_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('band_mid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('band_max', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_grade_id'], ['job_grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_band_job_grade_id'), 'salary_band', ['job_grade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_band_job_grade_id'), table_name='salary_band')
    op.drop_table('salary_band')
    op.drop_index(op.f('ix_employee_org_unit_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_job_grade_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_emp_no'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_pay_period_year_month'), table_name='pay_period')
    op.drop_table('pay_period')
    op.drop_index(op.f('ix_org_unit_parent_id'), table_name='org_unit')
    op.drop_table('org_unit')
    op.drop_table('job_grade')
    # drop_table 不会删除 Postgres 原生 enum 类型；显式删除以保证可重复 upgrade。
    bind = op.get_bind()
    for enum_name in ('employee_status', 'employment_type', 'period_status', 'org_type'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
