"""S10 attendance and performance

Revision ID: dcccc3935a7e
Revises: 2797ca8c8660
Create Date: 2026-07-19 22:48:12.818064

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dcccc3935a7e'
down_revision: str | None = '2797ca8c8660'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_record',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('expected_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('actual_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('leave_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('late_count', sa.Integer(), nullable=False),
    sa.Column('early_leave_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'period', name='uq_attendance_emp_period')
    )
    op.create_index(op.f('ix_attendance_record_employee_id'), 'attendance_record', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_period'), 'attendance_record', ['period'], unique=False)
    op.create_table('performance_record',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'period', name='uq_performance_emp_period')
    )
    op.create_index(op.f('ix_performance_record_employee_id'), 'performance_record', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_record_period'), 'performance_record', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_record_period'), table_name='performance_record')
    op.drop_index(op.f('ix_performance_record_employee_id'), table_name='performance_record')
    op.drop_table('performance_record')
    op.drop_index(op.f('ix_attendance_record_period'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_employee_id'), table_name='attendance_record')
    op.drop_table('attendance_record')
    # ### end Alembic commands ###
